#!/bin/sh
# I used this to run Hugo to develop the demonstration website. It was in a file alongside a folder called 'data' where the site contents were actually developed.
docker run --rm -it -p 1313:1313 --user "$(id -u):$(id -g)" -v $(pwd):/src klakegg/hugo:ext-alpine shell
